### ISSUE TITLE
Planed features

### ISSUE THREAD

**Issue by badwolfie** [badwolfie/quetzal#1]
#### Initial build (basic text editor functions)
- [x] Define window layout
- [x] File openning
- [x] File editing
- [ ] File saving
- [ ] File closing
- [x] Action undoing
- [x] Action redoing
- [x] About dialog
#### Milestones for v1.0:
- [ ] Syntax highlighting
- [ ] Change style scheme
- [ ] Change text font and size
- [ ] Change syntax highlighting while editing
- [ ] Color schemes
- [ ] Word completion
- [ ] Statusbar support
- [ ] Detect changes
- [ ] Tab support
- [ ] Re-open last closed tab
- [ ] Basic project building (using make)
- [ ] Text searching
- [ ] Embeeded terminal
- [ ] Terminal resizing
- [ ] Drag n' drop support
- [x] Support for dconf settings
- [ ] Reopen last session files
- [ ] Dark theme variant
- [ ] Full-screen mode
- [ ] Preferences dialog
- [ ] Translations
#### Milestone for v1.1:
- [ ] Reload files upon external modification
#### Milestone for v1.2:
- [ ] Overview minimap
#### Milestone for v1.3:
- [ ] Brace completion
#### Milestone for v1.4:
- [ ] Current folder/project Treeview
#### Milestone for v1.5:
- [ ] Basic code completion for C/C++

**_More to be defined...**_
